spring:
  datasource:
    url: jdbc:sqlite:./data/shiftbot.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
        jdbc:
          time_zone: UTC
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

bot:
  token: ${BOT_TOKEN:}
  username: ${BOT_USERNAME:}

audit:
  enabled: true
  chat-id: ${AUDIT_CHAT_ID:0}

tm:
  pin: ${TM_PIN:2525}

logging:
  level:
    esvar.ua.workinghoursbot: INFO


domain:
  tm:
    pin: ${TM_PIN:2525}
    max-attempts: ${TM_MAX_ATTEMPTS:3}
  schedule:
    max-sellers-per-location: ${SCHEDULE_MAX_SELLERS_PER_LOCATION:2}
